language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir -p build && cd build && cmake ..

script: 
  - cd build && make

install: true

branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - RVM=2.0.0 LANG="zh_CN.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
